### ISSUE TITLE
fail to convert point cloud data from one infrastructure coordinate system to vanother infrastructure coordinate system.

### ISSUE THREAD

**Issue by liyn69** [AIR-THU/DAIR-RCooper#13]
Thanks for your excellent work!
I want to conduct early fusion experiments on the rcooper dataset based on the opendairv2x framework. When I converted rcooper to dair-v2x dataset format according to your guidance, the structure is shown in the following figure:
![image](https://github.com/AIR-THU/DAIR-RCooper/assets/57906513/0b164d1c-97c9-43a4-a966-240ab1d5418c)

Then I follow https://github.com/AIR-THU/DAIR-V2X/tree/main/configs/vic3d/early-fusion-pointcloud/pointpillars guidelines to convert point cloud data from infrastructure coordinate system to vehicle coordinate system.But I found that the coordinate origin of the infrastructure dataset converted from the calibration matrix is different from another infrastructure dataset, making it impossible to Concate converted infrastructure-side point cloud data with another infrastructure-side point cloud data.

Do you know how I can solve this problem?I would greatly appreciate it if someone could help me solve this problem.

**Comment by leofansq** [comment]
Really glad that our work is valuable for you!
Actually, we evaluated the detection methods using OpenCOOD and V2V4Real framework. Since OpendairV2X framework only supports two agents (infrastructure or vehicle) for now, while there are four agents in RCooper's intersection scenario, we recommend to follow our README for detection benchmark.
Addressing the problem you mentioned, we will identify the problem and keep updating the corresponding code.
